
//获取pdf图片

export const GET_PARTICIPANTSLIST = 'GET_PARTICIPANTSLIST'
export const SET_CURRENTEDITPARTICIPANT = 'SET_CURRENTEDITPARTICIPANT'
export const GET_SEEARBITRATE = 'GET_SEEARBITRATE'
export const GET_EDITARBITRATE='GET_EDITARBITRATE'
export const GET_ADDARBITRATE='GET_ADDARBITRATE'
export const GET_BASESTR='GET_BASESTR'
export const GET_CASESLIST = 'GET_CASESLIST'
