
//查询仲裁委列表
export const GET_RELATEGETORG = 'GET_RELATEGETORG'
//设置当前选择的仲裁委
export const SET_CURRENTSELECTORG = 'SET_CURRENTSELECTORG'
export const SET_CURRENTCASEID = 'SET_CURRENTCASEID'
export const GET_APPLICANTS = 'GET_APPLICANTS'
export const GET_RESPONDENTLIST = 'GET_RESPONDENTLIST'
export const GET_AGENTS = 'GET_AGENTS'
export const GET_CONTRACT ='GET_CONTRACT'
export const SET_CURRENTEDITCONTRACT ='SET_CURRENTEDITCONTRACT'
//代理人==start
export const SET_CURRENTEDITAGENT ='SET_CURRENTEDITAGENT'
//代理人==end

//证据相关==start
export const SET_EVIDENCELIST = 'SET_EVIDENCELIST'
export const SET_CURRENTEDITEVIDENCE ='SET_CURRENTEDITEVIDENCE'
//证据相关==end

// 请求相关==start
export const SET_CLAIMLIST = 'SET_CLAIMLIST'
export const SET_CURRENTEDITCLAIM ='SET_CURRENTEDITCLAIM'
export const GET_CLAIMLISTRESONS ='GET_CLAIMLISTRESONS'
//请求相关==end


// 案例详情==start
export const SET_CASEDETAIL = 'SET_CASEDETAIL'
//案例详情==end
